function op_out = coherence_plotting(coh, op)
% COHERENCE_PLOTTING Plots trial-aligned, time-frequency coherence across electrode region pairs.
%
% Usage:
%   op_out = coherence_plotting(coh, op)
%
% Inputs:
%   coh - Table generated by ephys_coherence.m containing inter-regional electrode pairs
%         and nested time-frequency coherence tables.
%
%   op  - Options structure specifying plotting parameters:
%           .sync_event                  : String specifying the trial event to align to (e.g., 'speech_onset')
%           .sort_cond_vals              : Cell array or vector specifying condition values to plot and display order
%           .regions_to_analyze          : Cell array of region strings to include (e.g., {'IFG/IFS', 'STN'})
%           .tuning_param                : String or cell array of column names in coh containing electrode tuning p-values
%           .tuning_alpha                : Threshold(s) for tuning significance (scalar or vector, default 0.05)
%           .min_tuned_elcs              : Minimum number of tuned electrodes in pair required (0, 1, or 2; default 1)
%           .min_responsive_elcs         : Minimum number of task-responsive electrodes in pair (rspv == 1; default 0)
%           .norm_method                 : Coherence transform method - 'zscore_atanh' (default), 'zscore_base', or 'none'
%           .zscore_base_window          : 2-element vector [t_start, t_end] in seconds relative to sync event (required if 'zscore_base')
%           .yscale_mode                 : Frequency axis scaling - 'linear' (default) or 'equal'
%           .freq_range                  : 2-element vector [f_min, f_max] in Hz (optional; if empty/omitted, uses all frequencies)
%           .clim                        : [cmin, cmax] color scale bounds for heatmaps (optional)
%           .show_heatmap                : Logical (default true); if false, bypasses time-frequency heatmap generation
%           .show_canon_timecourses      : Logical (default false); if true, plots condition-overlaid timecourses for canonical bands
%           .canon_bands                 : Cell array of name-range pairs specifying custom frequency bands for timecourses
%                                          Accepts flat cell arrays, N x 2 cell arrays, or struct arrays.
%           .smooth_timecourse_width_sec : Scalar (default 0); if > 0, applies moving smoothing over window size in seconds
%           .smooth_timecourse_method    : String - 'mean' (default) or 'median' specifying smoothing filter type
%
% Outputs:
%   op_out - Output structure containing:
%           .figs                : Array of created figure handles
%           .op                  : Parsed options structure
%           .canonical_pairs     : Unique canonical region pairs plotted

%% =======================================================================
%% 1. DEFAULT OPTION ASSIGNMENTS & INPUT VALIDATION
%% =======================================================================
if nargin < 2 || isempty(op)
    op = struct();
end

% Validate sync_event
if ~isfield(op, 'sync_event') || isempty(op.sync_event)
    error('coherence_plotting:MissingSyncEvent', ...
        'op.sync_event must be specified (e.g., op.sync_event = ''speech_onset'').');
end

% Plot mode options
if ~isfield(op, 'show_heatmap') || isempty(op.show_heatmap)
    op.show_heatmap = true;
end

if ~isfield(op, 'show_canon_timecourses') || isempty(op.show_canon_timecourses)
    op.show_canon_timecourses = false;
end

if ~op.show_heatmap && ~op.show_canon_timecourses
    warning('coherence_plotting:NoPlotSelected', ...
        'Both op.show_heatmap and op.show_canon_timecourses are false. No plots rendered.');
end

% Timecourse smoothing options default
if ~isfield(op, 'smooth_timecourse_width_sec') || isempty(op.smooth_timecourse_width_sec)
    op.smooth_timecourse_width_sec = 0;
end

if ~isfield(op, 'smooth_timecourse_method') || isempty(op.smooth_timecourse_method)
    op.smooth_timecourse_method = 'mean';
end

valid_smooth_methods = {'mean', 'median'};
if ~ismember(lower(string(op.smooth_timecourse_method)), valid_smooth_methods)
    error('coherence_plotting:InvalidSmoothMethod', ...
        'Invalid op.smooth_timecourse_method ''%s''. Valid options: ''mean'', ''median''.', string(op.smooth_timecourse_method));
end

% Normalization method validation
if ~isfield(op, 'norm_method') || isempty(op.norm_method)
    op.norm_method = 'zscore_atanh';
end

valid_norm_methods = {'zscore_atanh', 'zscore_base', 'none'};
if ~ismember(op.norm_method, valid_norm_methods)
    error('coherence_plotting:InvalidNormMethod', ...
        'Invalid op.norm_method ''%s''. Valid options: ''zscore_atanh'', ''zscore_base'', ''none''.', op.norm_method);
end

if strcmp(op.norm_method, 'zscore_base')
    if ~isfield(op, 'zscore_base_window') || length(op.zscore_base_window) ~= 2
        error('coherence_plotting:MissingBaseWindow', ...
            'For ''zscore_base'' normalization, op.zscore_base_window must be a 2-element vector [t_start, t_end] in seconds.');
    end
end

% Frequency y-scale mode
if ~isfield(op, 'yscale_mode') || isempty(op.yscale_mode)
    op.yscale_mode = 'linear';
end

% Frequency range default
if ~isfield(op, 'freq_range')
    op.freq_range = [];
end

% Responsivity requirement default
if ~isfield(op, 'min_responsive_elcs') || isempty(op.min_responsive_elcs)
    op.min_responsive_elcs = 0;
end

% Sort condition values default
if ~isfield(op, 'sort_cond_vals')
    op.sort_cond_vals = {};
end

% Regions to analyze default
if ~isfield(op, 'regions_to_analyze')
    op.regions_to_analyze = {};
end

%% =======================================================================
%% 2. REGION PAIR CANONIZATION & INCLUSION FILTERING
%% =======================================================================
npairs = height(coh);
if npairs == 0
    error('coherence_plotting:EmptyTable', 'Input coh table is empty.');
end

% Canonize region pairs (Directionality invariant: order does not matter)
canonical_pairs = strings(npairs, 1);
for i = 1:npairs
    r1 = char(coh.region(i, 1));
    r2 = char(coh.region(i, 2));
    sorted_regs = sort({r1, r2});
    canonical_pairs(i) = sprintf('%s - %s', sorted_regs{1}, sorted_regs{2});
end

% Master logical mask for valid electrode pairs
valid_pair_mask = true(npairs, 1);

% Filter A: Region Inclusion Criteria
if ~isempty(op.regions_to_analyze)
    target_regs = cellstr(op.regions_to_analyze);
    for i = 1:npairs
        r1 = char(coh.region(i, 1));
        r2 = char(coh.region(i, 2));
        if ~ismember(r1, target_regs) || ~ismember(r2, target_regs)
            valid_pair_mask(i) = false;
        end
    end
end

% Filter B: Task Responsivity Criteria (rspv column check)
if op.min_responsive_elcs > 0
    if ismember('rspv', coh.Properties.VariableNames)
        rspv_data = coh.rspv; % Npairs x 2 matrix
        for i = 1:npairs
            n_rspv = sum(rspv_data(i, :) == 1);
            if n_rspv < op.min_responsive_elcs
                valid_pair_mask(i) = false;
            end
        end
    else
        warning('coherence_plotting:RspvMissing', ...
            'op.min_responsive_elcs requested, but column ''rspv'' is missing in coh table.');
    end
end

% Filter C: Multiple Tuning Parameters Criteria (Logical AND across parameters)
if isfield(op, 'tuning_param') && ~isempty(op.tuning_param)
    tuning_params = cellstr(op.tuning_param);
    n_params = length(tuning_params);
    
    % Expand tuning_alpha if scalar
    if ~isfield(op, 'tuning_alpha') || isempty(op.tuning_alpha)
        alphas = repmat(0.05, 1, n_params);
    elseif isscalar(op.tuning_alpha)
        alphas = repmat(op.tuning_alpha, 1, n_params);
    else
        alphas = op.tuning_alpha;
    end
    
    % Expand min_tuned_elcs if scalar
    if ~isfield(op, 'min_tuned_elcs') || isempty(op.min_tuned_elcs)
        min_tuned = repmat(1, 1, n_params);
    elseif isscalar(op.min_tuned_elcs)
        min_tuned = repmat(op.min_tuned_elcs, 1, n_params);
    else
        min_tuned = op.min_tuned_elcs;
    end
    
    for p = 1:n_params
        p_name = tuning_params{p};
        if ismember(p_name, coh.Properties.VariableNames)
            param_vals = coh.(p_name); % Npairs x 2 matrix
            p_alpha = alphas(p);
            p_min_req = min_tuned(p);
            
            for i = 1:npairs
                n_tuned = sum(param_vals(i, :) < p_alpha);
                if n_tuned < p_min_req
                    valid_pair_mask(i) = false;
                end
            end
        else
            warning('coherence_plotting:TuningParamMissing', ...
                'Tuning parameter column ''%s'' not found in coh table.', p_name);
        end
    end
end

%% =======================================================================
%% 3. EXTRACT TIME, FREQUENCY, AND CONDITION COORDINATES
%% =======================================================================
sample_pair_idx = find(valid_pair_mask, 1);
if isempty(sample_pair_idx)
    error('coherence_plotting:NoValidPairs', 'No electrode pairs met the specified tuning and region criteria.');
end

event_tbl = coh.coh{sample_pair_idx};
if ismember('event', event_tbl.Properties.VariableNames)
    ev_idx = find(strcmp(string(event_tbl.event), string(op.sync_event)), 1);
else
    ev_idx = find(strcmp(string(event_tbl.Properties.RowNames), string(op.sync_event)), 1);
end

if isempty(ev_idx)
    error('coherence_plotting:SyncEventNotFound', ...
        'Sync event ''%s'' not found in coh nested table.', op.sync_event);
end

% Extract time vector
time_vec = event_tbl{ev_idx, 'time'}{1};
ntimes = length(time_vec);

% Extract condition values
trialconds_tbl = event_tbl{ev_idx, 'trialconds'}{1};
if ~isempty(op.sort_cond_vals)
    cond_values = op.sort_cond_vals;
else
    raw_conds = trialconds_tbl.cond;
    if iscell(raw_conds) || isstring(raw_conds)
        cond_values = cellstr(raw_conds);
    else
        cond_values = num2cell(raw_conds);
    end
end
nconds = length(cond_values);

% Extract full frequency vector from first condition
freqs_tbl = trialconds_tbl{1, 'freqs'}{1};
raw_freq_vec = freqs_tbl.freq(:);

% Filter frequencies based on op.freq_range
if ~isfield(op, 'freq_range') || isempty(op.freq_range)
    freq_mask = true(size(raw_freq_vec));
else
    if length(op.freq_range) ~= 2
        error('coherence_plotting:InvalidFreqRange', ...
            'op.freq_range must be a 2-element vector [f_min, f_max] in Hz.');
    end
    f_min = min(op.freq_range);
    f_max = max(op.freq_range);
    freq_mask = (raw_freq_vec >= f_min) & (raw_freq_vec <= f_max);
    
    if ~any(freq_mask)
        error('coherence_plotting:NoFreqsInRange', ...
            'No frequencies in coh table fall within specified op.freq_range [%g, %g] Hz.', f_min, f_max);
    end
end

freq_vec = raw_freq_vec(freq_mask);
nfreqs = length(freq_vec);

% Pre-calculate bin edges for 'linear' yscale mode using pcolor
freq_edges = zeros(nfreqs + 1, 1);
freq_edges(2:end-1) = (freq_vec(1:end-1) + freq_vec(2:end)) / 2;
freq_edges(1) = freq_vec(1) - (freq_edges(2) - freq_vec(1));
freq_edges(end) = freq_vec(end) + (freq_vec(end) - freq_edges(end-1));

time_vec_col = time_vec(:);
time_edges = zeros(ntimes + 1, 1);
time_edges(2:end-1) = (time_vec_col(1:end-1) + time_vec_col(2:end)) / 2;
time_edges(1) = time_vec_col(1) - (time_edges(2) - time_vec_col(1));
time_edges(end) = time_vec_col(end) + (time_edges(end) - time_edges(end-1));

% Parse Frequency Bands (Flexible handling for flat cell, N x 2 cell, 2 x N cell, or struct)
default_canon_bands = struct(...
    'name', {'Delta', 'Theta', 'Alpha', 'Beta', 'Low Gamma', 'High Gamma'}, ...
    'fmin', {0.5, 4, 8, 12, 30, 70}, ...
    'fmax', {4, 8, 12, 30, 70, 150} ...
);

if isfield(op, 'canon_bands') && ~isempty(op.canon_bands)
    if iscell(op.canon_bands)
        cb_cell = op.canon_bands;
        
        if size(cb_cell, 2) == 2 && ~isvector(cb_cell)
            % N x 2 cell array format: {'Name', [fmin fmax]; ...}
            n_bands = size(cb_cell, 1);
            canon_bands = struct('name', cell(1, n_bands), 'fmin', cell(1, n_bands), 'fmax', cell(1, n_bands));
            for b = 1:n_bands
                b_name = cb_cell{b, 1};
                b_range = cb_cell{b, 2};
                
                if ~(ischar(b_name) || isstring(b_name))
                    error('coherence_plotting:InvalidCanonBands', ...
                        'Band name at row %d in op.canon_bands must be a string or char.', b);
                end
                if ~isnumeric(b_range) || length(b_range) ~= 2
                    error('coherence_plotting:InvalidCanonBands', ...
                        'Frequency range for band ''%s'' must be a 2-element vector [fmin fmax].', string(b_name));
                end
                
                canon_bands(b).name = char(b_name);
                canon_bands(b).fmin = min(b_range);
                canon_bands(b).fmax = max(b_range);
            end
            
        elseif size(cb_cell, 1) == 2 && ~isvector(cb_cell)
            % 2 x N cell array format: {'Name1', 'Name2'; [fmin1 fmax1], [fmin2 fmax2]}
            n_bands = size(cb_cell, 2);
            canon_bands = struct('name', cell(1, n_bands), 'fmin', cell(1, n_bands), 'fmax', cell(1, n_bands));
            for b = 1:n_bands
                b_name = cb_cell{1, b};
                b_range = cb_cell{2, b};
                
                if ~(ischar(b_name) || isstring(b_name))
                    error('coherence_plotting:InvalidCanonBands', ...
                        'Band name at column %d in op.canon_bands must be a string or char.', b);
                end
                if ~isnumeric(b_range) || length(b_range) ~= 2
                    error('coherence_plotting:InvalidCanonBands', ...
                        'Frequency range for band ''%s'' must be a 2-element vector [fmin fmax].', string(b_name));
                end
                
                canon_bands(b).name = char(b_name);
                canon_bands(b).fmin = min(b_range);
                canon_bands(b).fmax = max(b_range);
            end
            
        else
            % Flat vector cell array format: {'Name1', [fmin1 fmax1], 'Name2', [fmin2 fmax2], ...}
            if mod(numel(cb_cell), 2) ~= 0
                error('coherence_plotting:InvalidCanonBands', ...
                    'op.canon_bands cell array must contain pairs of ''BandName'', [fmin fmax].');
            end
            n_bands = numel(cb_cell) / 2;
            canon_bands = struct('name', cell(1, n_bands), 'fmin', cell(1, n_bands), 'fmax', cell(1, n_bands));
            for b = 1:n_bands
                b_name = cb_cell{2*b - 1};
                b_range = cb_cell{2*b};
                
                if ~(ischar(b_name) || isstring(b_name))
                    error('coherence_plotting:InvalidCanonBands', ...
                        'Band name at index %d in op.canon_bands must be a string or char.', 2*b-1);
                end
                if ~isnumeric(b_range) || length(b_range) ~= 2
                    error('coherence_plotting:InvalidCanonBands', ...
                        'Frequency range for band ''%s'' must be a 2-element vector [fmin fmax].', string(b_name));
                end
                
                canon_bands(b).name = char(b_name);
                canon_bands(b).fmin = min(b_range);
                canon_bands(b).fmax = max(b_range);
            end
        end
    elseif isstruct(op.canon_bands) && isfield(op.canon_bands, 'name') && ...
           isfield(op.canon_bands, 'fmin') && isfield(op.canon_bands, 'fmax')
        canon_bands = op.canon_bands;
    else
        error('coherence_plotting:InvalidCanonBands', ...
            'op.canon_bands must be a cell array of name-range pairs or a struct array.');
    end
else
    canon_bands = default_canon_bands;
end
n_canon_bands = length(canon_bands);

%% =======================================================================
%% 4. MULTI-MONITOR & DISPLAY SETUP
%% =======================================================================
monitor_positions = get(0, 'MonitorPositions');
num_monitors = size(monitor_positions, 1);

unique_canonical_pairs = unique(canonical_pairs(valid_pair_mask), 'stable');
npair_types = length(unique_canonical_pairs);

fig_handles = [];
fig_counter = 0;

switch op.norm_method
    case 'zscore_atanh'
        unit_label = 'Coherence (Fisher z)';
    case 'zscore_base'
        unit_label = 'Coherence (Baseline Z)';
    case 'none'
        unit_label = 'Coherence (Raw)';
end

%% =======================================================================
%% 5. PLOTTING BY UNIQUE CANONICAL REGION PAIRS
%% =======================================================================
for r = 1:npair_types
    reg_pair_label = unique_canonical_pairs(r);
    
    matching_pair_indices = find(strcmp(canonical_pairs, reg_pair_label) & valid_pair_mask);
    n_matching = length(matching_pair_indices);
    
    cond_matrices = cell(nconds, 1);
    pair_cond_matrices = cell(nconds, 1);
    
    for c = 1:nconds
        cond_val = cond_values{c};
        pair_stack = zeros(nfreqs, ntimes, n_matching);
        
        for ip = 1:n_matching
            pair_idx = matching_pair_indices(ip);
            p_ev_tbl = coh.coh{pair_idx};
            p_ev_row = p_ev_tbl{ev_idx, 'trialconds'}{1};
            
            if iscell(p_ev_row.cond) || isstring(p_ev_row.cond)
                c_row_idx = find(strcmp(string(p_ev_row.cond), string(unwrap_val(cond_val))), 1);
            else
                c_row_idx = find(p_ev_row.cond == unwrap_val(cond_val), 1);
            end
            
            if ~isempty(c_row_idx)
                p_freqs_tbl = p_ev_row{c_row_idx, 'freqs'}{1};
                p_coh = p_freqs_tbl.coh;
                pair_stack(:, :, ip) = p_coh(freq_mask, :);
            else
                pair_stack(:, :, ip) = NaN(nfreqs, ntimes);
            end
        end
        
        pair_norm = zeros(nfreqs, ntimes, n_matching);
        switch op.norm_method
            case 'zscore_atanh'
                C_bounded = min(max(pair_stack, 0), 0.9999);
                pair_norm = atanh(sqrt(C_bounded));
                
            case 'zscore_base'
                base_mask = (time_vec >= op.zscore_base_window(1)) & (time_vec <= op.zscore_base_window(2));
                if ~any(base_mask)
                    error('coherence_plotting:InvalidBaseWindow', ...
                        'op.zscore_base_window [%g %g] does not overlap with time vector.', ...
                        op.zscore_base_window(1), op.zscore_base_window(2));
                end
                
                for ip = 1:n_matching
                    C_pair = pair_stack(:, :, ip);
                    C_base = C_pair(:, base_mask);
                    mu_base = mean(C_base, 2, 'omitnan');
                    sigma_base = std(C_base, 0, 2, 'omitnan');
                    sigma_base(sigma_base == 0) = eps;
                    pair_norm(:, :, ip) = (C_pair - mu_base) ./ sigma_base;
                end
                
            case 'none'
                pair_norm = pair_stack;
        end
        
        pair_cond_matrices{c} = pair_norm;
        cond_matrices{c} = mean(pair_norm, 3, 'omitnan');
    end
    
    % OPTION A: TIME-FREQUENCY HEATMAPS
    if op.show_heatmap
        fig_counter = fig_counter + 1;
        target_mon_idx = num_monitors - mod(fig_counter - 1, num_monitors);
        target_pos = monitor_positions(target_mon_idx, :);
        
        fig_title_str = sprintf('Coherence Heatmap: %s', reg_pair_label);
        h_fig_hm = figure('Name', fig_title_str, 'Color', 'w', ...
                           'NumberTitle', 'off', 'Position', target_pos);
        drawnow;
        set(h_fig_hm, 'WindowState', 'maximized');
        fig_handles = [fig_handles; h_fig_hm];
        
        sgtitle(sprintf('Region Pair: %s  |  Sync Event: %s  (N = %d pairs)', ...
            reg_pair_label, op.sync_event, n_matching), ...
            'FontSize', 14, 'FontWeight', 'bold', 'Interpreter', 'none');
        
        N_cols = min(3, nconds);
        N_rows = ceil(nconds / N_cols);
        h_axes = zeros(nconds, 1);
        
        if isfield(op, 'clim') && ~isempty(op.clim)
            global_clim = op.clim;
        else
            all_vals = cell2mat(cellfun(@(m) m(:), cond_matrices, 'UniformOutput', false));
            global_clim = [min(all_vals, [], 'omitnan'), max(all_vals, [], 'omitnan')];
            if global_clim(1) == global_clim(2)
                global_clim = global_clim(1) + [-0.01, 0.01];
            end
        end
        
        for c = 1:nconds
            cond_val = cond_values{c};
            h_axes(c) = subplot(N_rows, N_cols, c);
            
            curr_row = ceil(c / N_cols);
            curr_col = mod(c - 1, N_cols) + 1;
            
            switch op.yscale_mode
                case 'linear'
                    C_pad = zeros(nfreqs + 1, ntimes + 1);
                    C_pad(1:nfreqs, 1:ntimes) = cond_matrices{c};
                    
                    pcolor(time_edges, freq_edges, C_pad);
                    shading flat;
                    axis tight;
                    yticks(auto_ticks(freq_vec));
                    
                case 'equal'
                    imagesc(time_vec, 1:nfreqs, cond_matrices{c});
                    axis xy;
                    yticks(1:nfreqs);
                    yticklabels(arrayfun(@(f) sprintf('%g', f), freq_vec, 'UniformOutput', false));
            end
            
            set(gca, 'YAxisLocation', 'left');
            colormap(gca, 'jet');
            clim(global_clim);
            hold on;
            
            xline(0, ':k', 'LineWidth', 1.2);
            hold off;
            
            cond_unwrapped = unwrap_val(cond_val);
            if isnumeric(cond_unwrapped) || islogical(cond_unwrapped)
                cond_title_str = sprintf('Condition: %g', cond_unwrapped);
            else
                cond_title_str = char(cond_unwrapped);
            end
            title(cond_title_str, 'FontSize', 13, 'FontWeight', 'bold', 'Interpreter', 'none');
            
            if curr_col == 1
                ylabel('Frequency (Hz)', 'FontSize', 11, 'FontWeight', 'bold');
            else
                ylabel('');
            end
            
            if curr_row == N_rows
                xlabel(sprintf('Time after %s (s)', op.sync_event), 'FontSize', 11, 'Interpreter', 'none');
            end
        end
        
        cb = colorbar(h_axes(min(N_cols, nconds)), 'Location', 'eastoutside');
        cb.Label.String = unit_label;
        cb.Label.FontSize = 10;
        cb.Label.FontWeight = 'bold';
        
        cb_pos = cb.Position;
        cb_pos(1) = 0.92;
        cb_pos(2) = 0.15;
        cb_pos(4) = 0.72;
        cb.Position = cb_pos;
    end
    
    % OPTION B: CANONICAL BAND TIMECOURSES OVERLAY
    if op.show_canon_timecourses
        fig_counter = fig_counter + 1;
        target_mon_idx = num_monitors - mod(fig_counter - 1, num_monitors);
        target_pos = monitor_positions(target_mon_idx, :);
        
        fig_title_str = sprintf('Canonical Timecourses: %s', reg_pair_label);
        h_fig_tc = figure('Name', fig_title_str, 'Color', 'w', ...
                           'NumberTitle', 'off', 'Position', target_pos);
        drawnow;
        set(h_fig_tc, 'WindowState', 'maximized');
        fig_handles = [fig_handles; h_fig_tc];
        
        sgtitle(sprintf('Region Pair: %s  |  Sync Event: %s  (N = %d pairs)', ...
            reg_pair_label, op.sync_event, n_matching), ...
            'FontSize', 14, 'FontWeight', 'bold', 'Interpreter', 'none');
        
        N_cols_tc = 3;
        N_rows_tc = ceil(n_canon_bands / N_cols_tc);
        
        cond_labels = cell(nconds, 1);
        for c = 1:nconds
            c_unwrapped = unwrap_val(cond_values{c});
            if isnumeric(c_unwrapped) || islogical(c_unwrapped)
                cond_labels{c} = sprintf('Cond %g', c_unwrapped);
            else
                cond_labels{c} = char(c_unwrapped);
            end
        end
        
        cond_colors = lines(nconds);
        dt = mean(diff(time_vec));
        
        for b = 1:n_canon_bands
            b_name = canon_bands(b).name;
            b_fmin = canon_bands(b).fmin;
            b_fmax = canon_bands(b).fmax;
            
            subplot(N_rows_tc, N_cols_tc, b);
            curr_row = ceil(b / N_cols_tc);
            hold on;
            
            band_freq_mask = (freq_vec >= b_fmin) & (freq_vec <= b_fmax);
            
            h_lines = zeros(nconds, 1);
            for c = 1:nconds
                if any(band_freq_mask)
                    p_norm = pair_cond_matrices{c};
                    pair_band_tc = mean(p_norm(band_freq_mask, :, :), 1, 'omitnan');
                    pair_tc_matrix = permute(pair_band_tc, [3, 2, 1]);
                else
                    pair_tc_matrix = nan(n_matching, ntimes);
                end
                
                % Optional timecourse smoothing (moving mean or moving median)
                if op.smooth_timecourse_width_sec > 0 && dt > 0
                    win_pts = round(op.smooth_timecourse_width_sec / dt);
                    if win_pts > 1
                        switch lower(string(op.smooth_timecourse_method))
                            case 'mean'
                                pair_tc_matrix = movmean(pair_tc_matrix, win_pts, 2, 'omitnan');
                            case 'median'
                                pair_tc_matrix = movmedian(pair_tc_matrix, win_pts, 2, 'omitnan');
                        end
                    end
                end
                
                mean_tc = mean(pair_tc_matrix, 1, 'omitnan');
                if n_matching > 1
                    std_tc = std(pair_tc_matrix, 0, 1, 'omitnan');
                    n_valid = sum(~isnan(pair_tc_matrix), 1);
                    sem_tc = std_tc ./ sqrt(n_valid);
                    sem_tc(isnan(sem_tc)) = 0;
                else
                    sem_tc = zeros(1, ntimes);
                end
                
                x_patch = [time_vec_col; flipud(time_vec_col)];
                uE = mean_tc(:) + sem_tc(:);
                lE = mean_tc(:) - sem_tc(:);
                y_patch = [uE; flipud(lE)];
                
                fill(x_patch, y_patch, cond_colors(c, :), ...
                    'FaceAlpha', 0.2, 'EdgeColor', 'none', 'HandleVisibility', 'off');
                
                h_lines(c) = plot(time_vec, mean_tc, 'LineWidth', 1.8, 'Color', cond_colors(c, :));
            end
            
            xline(0, ':k', 'LineWidth', 1.2);
            hold off;
            grid on;
            axis tight;
            
            ylabel_str = sprintf('Coherence [%s, %g-%g Hz]', b_name, b_fmin, b_fmax);
            ylabel(ylabel_str, 'FontSize', 10, 'FontWeight', 'bold');
            
            title(sprintf('%s (%g - %g Hz)', b_name, b_fmin, b_fmax), ...
                'FontSize', 12, 'FontWeight', 'bold');
            
            if curr_row == N_rows_tc
                xlabel(sprintf('Time after %s (s)', op.sync_event), 'FontSize', 11, 'Interpreter', 'none');
            end
            
            legend(h_lines, cond_labels, 'Interpreter', 'none', 'Location', 'best');
        end
    end
end

op_out.figs = fig_handles;
op_out.op = op;
op_out.canonical_pairs = unique_canonical_pairs;

end


%% =======================================================================
%% HELPER FUNCTIONS
%% =======================================================================

function val = unwrap_val(val)
while iscell(val) && numel(val) == 1
    val = val{1};
end
end

function ticks = auto_ticks(vec)
vec_range = max(vec) - min(vec);
if vec_range > 100
    ticks = min(vec):25:max(vec);
elseif vec_range > 40
    ticks = min(vec):10:max(vec);
else
    ticks = vec;
end
end